# Generated by Django 5.2.5 on 2026-06-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('client_name_manual', models.CharField(blank=True, help_text='Use if client not in Customer master', max_length=200)),
                ('technology', models.CharField(blank=True, help_text='e.g. Visual FoxPro, Django, PHP, .NET', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Live', help_text='e.g. Live, Stopped, Under Development, On Hold', max_length=100)),
                ('server_details', models.TextField(blank=True, help_text='Server IP, hosting provider, etc.')),
                ('login_url', models.CharField(blank=True, max_length=300)),
                ('login_username', models.CharField(blank=True, max_length=100)),
                ('login_password', models.CharField(blank=True, max_length=100)),
                ('payment_type', models.CharField(choices=[('onetime', 'One-Time Payment'), ('amc', 'AMC (Annual)'), ('subscription', 'Monthly Subscription')], default='onetime', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='One-time amount / AMC amount / Monthly fee', max_digits=12)),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('subscription_due_day', models.IntegerField(blank=True, help_text='Day of month payment is due (1-31)', null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(default='Pending', help_text='e.g. Paid, Pending, Overdue', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='masters.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(blank=True, help_text='Cash, Bank Transfer, UPI, Cheque', max_length=50)),
                ('period_covered', models.CharField(blank=True, help_text='e.g. Jan 2026, FY 2025-26', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
