# Generated by Django 5.2.5 on 2026-06-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_note', '0001_initial'),
        ('masters', '0003_credit_note_vfp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='add_less1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='add_less1_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='add_less2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='add_less2_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='gr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='gr_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='gst_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='gst_bill_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='gst_type',
            field=models.CharField(choices=[('I', 'Inter State'), ('W', 'Within State')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='net_rounded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='discount_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='hsn_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='sale_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.product'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
