# Generated by Django 5.2.5 on 2026-06-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_note', '0002_credit_note_vfp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='dis_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='gst_on_freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='gst_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice_date_text',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice_number_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='transport',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
