# Generated by Django 5.2.5 on 2026-06-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_masters_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalledgermaster',
            options={'ordering': ['description']},
        ),
    ]
