# Generated by Django 5.2.5 on 2026-06-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('gst', 'GST Invoice'), ('proforma', 'Proforma'), ('export', 'Export Invoice')], default='gst', max_length=10)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('CAD', 'Canadian Dollar')], default='INR', max_length=3)),
                ('usd_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cad_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('port_of_loading', models.CharField(blank=True, max_length=100)),
                ('port_of_discharge', models.CharField(blank=True, max_length=100)),
                ('country_of_destination', models.CharField(blank=True, max_length=100)),
                ('shipping_bill_no', models.CharField(blank=True, max_length=50)),
                ('lut_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.customer')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('rate_cad', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_cad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
            ],
        ),
    ]
