# Generated by Django 5.2.5 on 2026-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='add_less1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='add_less1_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='add_less2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='add_less2_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='date_of_supply',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='despatched_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='gr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='gr_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='net_rounded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='order_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='reverse_charge',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='time_of_supply',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='transport',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='hsn_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
