# Generated by Django 5.2.5 on 2026-06-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sales_discount_gsttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='customer_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
