# Generated by Django 5.2.5 on 2026-06-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_customer_mobile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
